name: rcti

on:

  schedule:

    - cron: '00 00/2 * * *'

  pull_request:

    branches:

      - master

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repo

        uses: actions/checkout@v2

      - name: config

        run: |

          git pull

          git config --global user.email "sudiana111@gmail.com"

          git config --global user.name "nontonyuk"

      - name: update play-yt

        run: |

          pwd

          mkdir tmp

          wget -U 'okhttp/1.2' -qP tmp https://playlist-coffee.my.id/github/rcti.py

          python3 tmp/rcti.py --channel-name rcti rcti.m3u8

          python3 tmp/rcti.py --channel-name mnctv mnctv.m3u8

          python3 tmp/rcti.py --channel-name gtv gtv.m3u8

          python3 tmp/rcti.py --channel-name inews inews.m3u8

          

          rm -rf tmp

      - name: commit

        run: |

          git add -A

          git commit -m "Update play-yt"

          git push
